# Generated by Django 2.2.24 on 2022-02-14 11:12

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20220214_1054'),
        ('base', '0029_auto_20220214_1112'),
        ('layers', '24_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='featureinfo_type',
            field=models.CharField(choices=[('type_property', 'Label'), ('type_href', 'URL'), ('type_image', 'Image'), ('type_video_mp4', 'Video (mp4)'), ('type_video_ogg', 'Video (ogg)'), ('type_video_webm', 'Video (webm)'), ('type_video_3gp', 'Video (3gp)'), ('type_video_flv', 'Video (flv)'), ('type_video_youtube', 'Video (YouTube/VIMEO - embedded)'), ('type_audio', 'Audio'), ('type_iframe', 'IFRAME')], default='type_property', help_text='specifies if the attribute should be rendered with an HTML widget on GetFeatureInfo template.', max_length=255, verbose_name='featureinfo type'),
        ),
        migrations.AddField(
            model_name='layer',
            name='elevation_regex',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Elevation regex'),
        ),
        migrations.AddField(
            model_name='layer',
            name='featureinfo_custom_template',
            field=tinymce.models.HTMLField(blank=True, help_text='the custom GetFeatureInfo template HTML contents.', null=True, verbose_name='featureinfo custom template'),
        ),
        migrations.AddField(
            model_name='layer',
            name='has_elevation',
            field=models.BooleanField(default=False, verbose_name='Has elevation?'),
        ),
        migrations.AddField(
            model_name='layer',
            name='has_time',
            field=models.BooleanField(default=False, verbose_name='Has time?'),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_mosaic',
            field=models.BooleanField(default=False, verbose_name='Is mosaic?'),
        ),
        migrations.AddField(
            model_name='layer',
            name='remote_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_regex',
            field=models.CharField(blank=True, choices=[('[0-9]{8}', 'YYYYMMDD'), ('[0-9]{8}T[0-9]{6}', "YYYYMMDD'T'hhmmss"), ('[0-9]{8}T[0-9]{6}Z', "YYYYMMDD'T'hhmmss'Z'")], max_length=128, null=True, verbose_name='Time regex'),
        ),
        migrations.AddField(
            model_name='layer',
            name='use_featureinfo_custom_template',
            field=models.BooleanField(default=False, help_text='specifies wether or not use a custom GetFeatureInfo template.', verbose_name='use featureinfo custom template?'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='constraints_other_en',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='Restrictions other'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_quality_statement_en',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='Data quality statement'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='default_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_default_style', to='layers.Style'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='purpose_en',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='store',
            field=models.CharField(max_length=128, verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='storeType',
            field=models.CharField(max_length=128, verbose_name='Storetype'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='supplemental_information_en',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='Supplemental information'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='typename',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Typename'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='workspace',
            field=models.CharField(max_length=128, verbose_name='Workspace'),
        ),
        migrations.AlterField(
            model_name='layerfile',
            name='file',
            field=models.FileField(max_length=4096, storage=django.core.files.storage.FileSystemStorage(base_url='/uploaded/'), upload_to='layers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='layerfile',
            name='name',
            field=models.CharField(max_length=4096),
        ),
    ]
