# Generated by Django 2.2.27 on 2022-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0026_auto_20220511_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='supplemental_information_en',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the Dataset.', max_length=2000, null=True, verbose_name='Supplemental Information'),
        ),
    ]
