# Generated by Django 3.2.14 on 2022-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0028_auto_20220512_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='user',
        ),
        migrations.AddField(
            model_name='layer',
            name='ows_url',
            field=models.URLField(blank=True, help_text='The URL of the OWS service providing this layer, if any exists.', null=True, verbose_name='ows URL'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('store', 'workspace', 'name')},
        ),
        migrations.DeleteModel(
            name='LayerFile',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='upload_session',
        ),
        migrations.DeleteModel(
            name='UploadSession',
        ),
    ]
