# Generated by Django 3.2.14 on 2022-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0029_auto_20220725_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='supplemental_information_en',
            field=models.TextField(blank=True, help_text='any other descriptive information about the Dataset.', max_length=2000, null=True, verbose_name='Supplemental Information'),
        ),
    ]
