# Generated by Django 2.2.27 on 2022-03-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoNodeThemeCustomization',
        ),
    ]
