# Generated by Django 2.2.27 on 2022-03-09 04:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumbotronThemeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255, unique=True)),
                ('jumbotron_slide_image', models.ImageField(upload_to='img/%Y/%m', verbose_name='Jumbotron slide background')),
                ('jumbotron_slide_content', models.TextField(blank=True, help_text='Fill in this section with markdown', null=True, verbose_name='Jumbotron slide content')),
                ('hide_jumbotron_slide_content', models.BooleanField(default=False, help_text='Check this if the jumbotron background image already contains text', verbose_name='Hide text in the jumbotron slide')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabling this slide will hide it from the slide show')),
            ],
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='contact_facsimile',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='contact_voice',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_site_description',
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='body_text_color',
            field=colorfield.fields.ColorField(default='#3a3a3a', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_accept_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_animate_speed_hide',
            field=models.CharField(default='500', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_animate_speed_show',
            field=models.CharField(default='500', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_as_popup',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_background',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_enabled',
            field=models.BooleanField(default=True, verbose_name='Cookies Law Info Bar'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_head',
            field=models.TextField(default='This website uses cookies'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_heading_text',
            field=models.CharField(default='This website uses cookies', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_text',
            field=models.TextField(default='This website uses cookies to improve your experience,         check <strong><a style="color:#000000" href="/privacy-policy/">this page</a></strong> for details.         We\'ll assume you\'re ok with this, but you can opt-out if you wish.'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_border',
            field=colorfield.fields.ColorField(default='#444', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_border_on',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_new_win',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_button_colour',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_hidebar',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_new_win',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_cookie_bar_as',
            field=models.CharField(default='banner', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller',
            field=models.TextField(default='#DATA_CONTROLLER'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_address',
            field=models.TextField(default='#DATA_CONTROLLER_ADDRESS'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_email',
            field=models.TextField(default='#DATA_CONTROLLER_EMAIL'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_phone',
            field=models.TextField(default='#DATA_CONTROLLER_PHONE'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_font_family',
            field=models.CharField(default='inherit', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_header_fix',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_leave_url',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_link_text',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_logging_on',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_animate_hide',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_animate_show',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_div_id',
            field=models.CharField(default='#cookie-law-info-bar', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_position_horizontal',
            field=models.CharField(default='right', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_position_vertical',
            field=models.CharField(default='bottom', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_popup_overlay',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_popup_showagain_position',
            field=models.CharField(default='bottom-right', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_reject_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_scroll_close',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_scroll_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_show_once',
            field=models.CharField(default='10000', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_show_once_yn',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_background',
            field=models.CharField(default='#fff', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_border',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_div_id',
            field=models.CharField(default='#cookie-law-info-again', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_head',
            field=models.TextField(default='Privacy & Cookies Policy'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_tab',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_x_position',
            field=models.CharField(default='30px', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_text',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_widget_position',
            field=models.CharField(default='left', max_length=30),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color of the footer, default to black', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_href_color',
            field=colorfield.fields.ColorField(default='#ff8f31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='jumbotron_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='jumbotron_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Display logo at the footer', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='modal_login_bg',
            field=models.ImageField(blank=True, help_text='Display image at the login window', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_divider',
            field=colorfield.fields.ColorField(default='#eea200', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_hover',
            field=colorfield.fields.ColorField(default='#eea200', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_text',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover_focus',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_link_color',
            field=colorfield.fields.ColorField(default='#ff8f31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='textbox_bg_color',
            field=colorfield.fields.ColorField(default='#1c4742', help_text='Background color of textbox input, default to green', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='textbox_input_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Text color of textbox input, default to white', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='welcome_theme',
            field=models.CharField(choices=[('JUMBOTRON_BG', 'jumbotron background'), ('SLIDE_SHOW', 'slide show')], default='JUMBOTRON_BG', help_text='Choose between using jumbotron background and slide show', max_length=255),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_administrative_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_delivery_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contact_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='contactus',
            field=models.BooleanField(default=False, verbose_name='Enable contact us box'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='copyright_color',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='This will not appear anywhere.'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='description',
            field=models.TextField(blank=True, help_text='This will not appear anywhere.', null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Enabling this theme will disable the current enabled theme (if any)'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_bg',
            field=models.ImageField(blank=True, help_text='Display background image at the landing page', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_color',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_content',
            field=models.TextField(blank=True, help_text='Landing page welcome title', null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_hide',
            field=models.BooleanField(default=False, help_text='Check this if the jumbotron backgroud image already contains text', verbose_name='Hide text in the jumbotron'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_title',
            field=models.CharField(blank=True, help_text='Landing page title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Display logo at the navigation header', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='name',
            field=models.CharField(help_text='This will not appear anywhere.', max_length=100),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color of the navigation bar, default to black', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='partner',
            name='href',
            field=models.CharField(max_length=255, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='This will not appear anywhere.', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='jumbotron_slide_show',
            field=models.ManyToManyField(blank=True, to='geonode_themes.JumbotronThemeSlide'),
        ),
    ]
