# Generated by Django 2.2.27 on 2022-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdi_themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('id',), 'verbose_name_plural': 'SDI Feedbacks'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='reported_by',
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='help',
            name='created_date',
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='about',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='faq',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='help',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='help',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created Date'),
        ),
    ]
