# Generated by Django 2.2.27 on 2022-05-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
    ]
