# Generated by Django 2.2.27 on 2022-03-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0002_auto_20220309_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Display favicon ico at browser tab', null=True, upload_to='img/%Y/%m'),
        ),
    ]
