# Generated by Django 2.2.27 on 2022-06-14 06:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_auto_20220609_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='showcase_bg_color',
            field=colorfield.fields.ColorField(default='#1C463F', help_text='Background color of the showcase landing page, default to green', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_bg_color',
            field=colorfield.fields.ColorField(default='#F0F2F5', help_text='Background color of textbox input, default to green', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_input_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Text color of textbox input, default to white', image_field=None, max_length=18, samples=None),
        ),
    ]
