# Generated by Django 2.2.27 on 2022-07-11 10:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20220614_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#1C463F', help_text='Background color of the header pages, default to green', image_field=None, max_length=18, samples=None, verbose_name='Header background color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='Search background color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='showcase_bg_color',
            field=colorfield.fields.ColorField(default='#1C463F', help_text='Background color of the showcase landing page, default to green', image_field=None, max_length=18, samples=None, verbose_name='Showcase background color'),
        ),
    ]
