# Generated by Django 2.2.27 on 2022-07-11 11:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20220614_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_color',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_text_color',
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#1C463F', help_text='Background color of the header pages, default to green', image_field=None, max_length=18, samples=None, verbose_name='Header background color'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='jumbotron_description_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Landing page long description color, default to white', image_field=None, max_length=18, samples=None, verbose_name='Landing page description color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color of the footer at the landing page, default to black', image_field=None, max_length=18, samples=None, verbose_name='Footer background color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_bg',
            field=models.ImageField(blank=True, help_text='Display background image at the landing page', null=True, upload_to='img/%Y/%m', verbose_name='Landing page background image'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Landing page welcome title color, default to white', image_field=None, max_length=18, samples=None, verbose_name='Landing page title color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_content',
            field=models.TextField(blank=True, help_text='Landing page long description, i.e.: Welcome to the Spatial Data Infrastructure', null=True, verbose_name='Landing page description'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_title',
            field=models.CharField(blank=True, help_text='Landing page welcome title, i.e.: Information Sharing Platform', max_length=255, null=True, verbose_name='Landing page title'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='modal_login_bg',
            field=models.ImageField(blank=True, help_text='Display image at the login window', null=True, upload_to='img/%Y/%m', verbose_name='Modal login background image'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='Search background color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='showcase_bg_color',
            field=colorfield.fields.ColorField(default='#1C463F', help_text='Background color of the showcase landing page, default to green', image_field=None, max_length=18, samples=None, verbose_name='Showcase background color'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_bg_color',
            field=colorfield.fields.ColorField(default='#F0F2F5', help_text='Background color of textbox input, default to green', image_field=None, max_length=18, samples=None, verbose_name='Textbox background color'),
        ),
    ]
