# Generated by Django 2.2.16 on 2021-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0011_auto_20200727_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='contact_facsimile',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='contact_voice',
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_background',
            field=models.CharField(default='#f0ab00', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_link_colour',
            field=models.CharField(default='#f0ab00', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_link_colour',
            field=models.CharField(default='#f0ab00', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_link_colour',
            field=models.CharField(default='#f0ab00', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_link_colour',
            field=models.CharField(default='#f0ab00', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='copyright_color',
            field=models.CharField(default='#f0ab00', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_color',
            field=models.CharField(default='#f0ab00', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu',
            field=models.CharField(default='#f0ab00', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_divider',
            field=models.CharField(default='#eea200', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_hover',
            field=models.CharField(default='#eea200', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover',
            field=models.CharField(default='#f0ab00', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover_focus',
            field=models.CharField(default='#f0ab00', max_length=10),
        ),
    ]
