# Generated by Django 2.2.27 on 2022-03-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0012_auto_20210524_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='body_color',
        ),
    ]
