# Generated by Django 2.2.27 on 2022-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0013_remove_geonodethemecustomization_body_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_cta_hide',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_cta_link',
        ),
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='jumbotron_cta_text',
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_bg_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_content',
            field=models.TextField(blank=True, null=True, verbose_name='Landing page welcome title'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landing page title'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
