# Generated by Django 2.2.27 on 2022-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0014_auto_20220308_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Display logo at footer', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_bg',
            field=models.ImageField(blank=True, help_text='Display background at the landing page', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_content',
            field=models.TextField(blank=True, help_text='Landing page welcome title', null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_welcome_title',
            field=models.CharField(blank=True, help_text='Landing page title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Display logo at navigation header', null=True, upload_to='img/%Y/%m'),
        ),
    ]
