# Generated by Django 2.2.27 on 2022-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0015_auto_20220308_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='textbox_input_color',
            field=models.CharField(default='#1c4742', help_text='Background color of textbox input, default to green', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_bg_color',
            field=models.CharField(default='#000000', help_text='Background color of the footer, default to black', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_color',
            field=models.CharField(default='#000000', help_text='Background color of the navigation bar, default to black', max_length=10),
        ),
    ]
