# Generated by Django 2.2.27 on 2022-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0016_auto_20220308_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='textbox_bg_color',
            field=models.CharField(default='#1c4742', help_text='Background color of textbox input, default to green', max_length=10),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_input_color',
            field=models.CharField(default='#ffffff', help_text='Text color of textbox input, default to white', max_length=10),
        ),
    ]
