# Generated by Django 2.2.27 on 2022-03-08 08:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0017_auto_20220308_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='body_text_color',
            field=colorfield.fields.ColorField(default='#3a3a3a', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_background',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_border',
            field=colorfield.fields.ColorField(default='#444', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_button_colour',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_button_colour',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_button_hover',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_link_colour',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_border',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_text',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='copyright_color',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color of the footer, default to black', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_href_color',
            field=colorfield.fields.ColorField(default='#ff8f31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_color',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color of the navigation bar, default to black', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_divider',
            field=colorfield.fields.ColorField(default='#eea200', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_hover',
            field=colorfield.fields.ColorField(default='#eea200', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_dropdown_menu_text',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='navbar_text_hover_focus',
            field=colorfield.fields.ColorField(default='#F39F1E', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_link_color',
            field=colorfield.fields.ColorField(default='#ff8f31', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='search_title_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_bg_color',
            field=colorfield.fields.ColorField(default='#1c4742', help_text='Background color of textbox input, default to green', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='textbox_input_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Text color of textbox input, default to white', image_field=None, max_length=18, samples=None),
        ),
    ]
