# Generated by Django 2.2.27 on 2022-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0018_auto_20220308_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_accept_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_as_popup',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_border_on',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_1_new_win',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_2_hidebar',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_3_new_win',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_button_4_as_button',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_header_fix',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_logging_on',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_animate_hide',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_notify_animate_show',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_popup_overlay',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_reject_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_scroll_close',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_scroll_close_reload',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_show_once_yn',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_showagain_tab',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=30),
        ),
    ]
