# Generated by Django 2.2.27 on 2022-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0019_auto_20220308_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_text',
            field=models.TextField(default='This website uses cookies to improve your experience,         check <strong><a style="color:#000000" href="/privacy-policy/">this page</a></strong> for details.         We\'ll assume you\'re ok with this, but you can opt-out if you wish.'),
        ),
    ]
