# Generated by Django 2.2.27 on 2022-03-08 08:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0020_auto_20220308_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
