# Generated by Django 2.2.27 on 2022-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0022_auto_20220308_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_bar_text',
            field=models.TextField(),
        ),
    ]
