# Generated by Django 2.2.27 on 2022-03-08 10:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0026_auto_20220308_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_link_text',
            field=colorfield.fields.ColorField(default='#00000', image_field=None, max_length=18, samples=None),
        ),
    ]
