# Generated by Django 2.2.27 on 2022-03-08 10:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0027_geonodethemecustomization_cookie_law_info_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_link_text',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_text',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
