# Generated by Django 2.2.27 on 2022-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0028_auto_20220308_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='modal_login_bg',
            field=models.ImageField(blank=True, help_text='Display image at the login window', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_bg',
            field=models.ImageField(blank=True, help_text='Display background image at the landing page', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Display logo at the navigation header', null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Display logo at the footer', null=True, upload_to='img/%Y/%m'),
        ),
    ]
