# Generated by Django 2.2.27 on 2022-05-10 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('contents', models.TextField(blank=True, help_text='Content of the About page', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'SDI About Site',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('contents', models.TextField(blank=True, help_text='Content of the Help & Support page', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'SDI Help & Support Site',
                'ordering': ('id',),
            },
        ),
    ]
