# Generated by Django 2.2.27 on 2022-03-08 13:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_monitoring_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OWS:TMS', 'TMS'), ('OWS:WMS-C', 'WMS-C'), ('OWS:WMTS', 'WMTS'), ('OWS:WCS', 'WCS'), ('OWS:WFS', 'WFS'), ('OWS:WMS', 'WMS'), ('OWS:WPS', 'WPS'), ('other', 'Not OWS'), ('OWS:ALL', 'Any OWS'), ('all', 'All'), ('create', 'Create'), ('upload', 'Upload'), ('change', 'Change'), ('change_metadata', 'Change Metadata'), ('view_metadata', 'View Metadata'), ('view', 'View'), ('download', 'Download'), ('publish', 'Publish'), ('remove', 'Remove'), ('geoserver', 'Geoserver event')], max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(help_text='Description of the alert', max_length=255)),
                ('user_threshold', models.JSONField(default=dict, help_text='Expected min/max values for user configuration')),
                ('last_send', models.DateTimeField(blank=True, help_text='Marker of last delivery', null=True)),
                ('grace_period', models.DurationField(choices=[(datetime.timedelta(seconds=60), '1 minute'), (datetime.timedelta(seconds=300), '5 minutes'), (datetime.timedelta(seconds=600), '10 minutes'), (datetime.timedelta(seconds=1800), '30 minutes'), (datetime.timedelta(seconds=3600), '1 hour')], default=datetime.timedelta(seconds=600), help_text='Minimum time between subsequent notifications')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], default='error', help_text='How severe would be error from this notification', max_length=32)),
                ('active', models.BooleanField(default=True, help_text='Is it active')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='ows_type',
        ),
        migrations.AddField(
            model_name='exceptionevent',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='metric',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='type',
            field=models.CharField(choices=[('rate', 'Rate'), ('count', 'Count'), ('value', 'Value'), ('value_numeric', 'Value numeric')], default='rate', max_length=255),
        ),
        migrations.AddField(
            model_name='metric',
            name='unit',
            field=models.CharField(blank=True, choices=[('B', 'Bytes'), ('KB', 'Kilobytes'), ('MB', 'Megabytes'), ('GB', 'Gigabytes'), ('B/s', 'Bytes per second'), ('KB/s', 'Kilobytes per second'), ('MB/s', 'Megabytes per second'), ('GB/s', 'Gigabytes per second'), ('s', 'Seconds'), ('Rate', 'Rate'), ('%', 'Percentage'), ('Count', 'Count')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriclabel',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoredresource',
            name='resource_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='user_username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionevent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='monitoring.RequestEvent'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='monitoring.MetricLabel'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='monitoring.MonitoredResource'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_num',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredresource',
            name='type',
            field=models.CharField(choices=[('', 'No resource'), ('layer', 'Layer'), ('map', 'Map'), ('resource_base', 'Resource base'), ('document', 'Document'), ('style', 'Style'), ('admin', 'Admin'), ('url', 'URL'), ('other', 'Other')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_lat',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_lon',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='request_path',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='resources',
        ),
        migrations.AddField(
            model_name='requestevent',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='List of resources affected', related_name='requests', to='monitoring.MonitoredResource'),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicetypemetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='monitoring.Metric'),
        ),
        migrations.AlterField(
            model_name='servicetypemetric',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='monitoring.ServiceType'),
        ),
        migrations.CreateModel(
            name='NotificationReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='monitoring.NotificationCheck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMetricDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_service', models.BooleanField(default=False)),
                ('use_resource', models.BooleanField(default=False)),
                ('use_label', models.BooleanField(default=False)),
                ('use_event_type', models.BooleanField(default=False)),
                ('field_option', models.CharField(choices=[('min_value', 'Value must be above'), ('max_value', 'Value must be below'), ('max_timeout', 'Last update must not be older than')], default='min_value', max_length=32)),
                ('description', models.TextField(null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_checks', to='monitoring.Metric')),
                ('notification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='monitoring.NotificationCheck')),
            ],
        ),
        migrations.AddField(
            model_name='notificationcheck',
            name='metrics',
            field=models.ManyToManyField(related_name='_notificationcheck_metrics_+', through='monitoring.NotificationMetricDefinition', to='monitoring.Metric'),
        ),
        migrations.CreateModel(
            name='MetricNotificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True)),
                ('max_timeout', models.DurationField(blank=True, help_text='Max timeout for given metric before error should be raised', null=True)),
                ('active', models.BooleanField(default=True)),
                ('definition', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_check', to='monitoring.NotificationMetricDefinition')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.EventType')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.MetricLabel')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.Metric')),
                ('notification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.NotificationCheck')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.MonitoredResource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.Service')),
            ],
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='monitoring.EventType'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.EventType'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together={('valid_from', 'valid_to', 'service', 'service_metric', 'resource', 'label', 'event_type')},
        ),
    ]
