# Generated by Django 3.2.14 on 2022-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20220308_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcheck',
            name='user_threshold',
            field=models.JSONField(default=dict, help_text='Expected min/max values for user configuration'),
        ),
    ]
