# Generated by Django 3.2.14 on 2022-09-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_notificationcheck_user_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredresource',
            name='type',
            field=models.CharField(choices=[('', 'No resource'), ('layer', 'Layer'), ('map', 'Map'), ('resource_base', 'Resource base'), ('dataset', 'Dataset'), ('style', 'Style'), ('admin', 'Admin'), ('url', 'URL'), ('other', 'Other')], default='', max_length=255),
        ),
    ]
