# Generated by Django 3.2.13 on 2022-04-18 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0026_auto_20220405_1505'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRequest',
            fields=[
                ('exec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('failed', 'failed'), ('running', 'running'), ('finished', 'finished')], default='ready', max_length=50)),
                ('func_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('input_params', models.JSONField(blank=True, default=dict)),
                ('output_params', models.JSONField(blank=True, default=dict)),
                ('geonode_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
