# Generated by Django 3.2.14 on 2022-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_executionrequest_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrequest',
            name='input_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='output_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
