# Generated by Django 2.2.27 on 2022-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '26_to_27'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('public-invite', 'Public (invite-only)'), ('private', 'Private')], default="public'", help_text='Public: Any registered user can view and join a public group.<br>Public (invite-only):Any registered user can view the group.  Only invited users can join.<br>Private: Registered users cannot see any details about the group, including membership.  Only invited users can join.', max_length=15, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.GroupCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
