# Generated by Django 2.2.27 on 2022-05-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0027_auto_20220308_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='created_by',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
