# Generated by Django 2.2.27 on 2022-05-15 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0028_auto_20220514_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='created_by',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
