# Generated by Django 2.2.27 on 2022-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_auto_20220515_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('public-invite', 'Public (invite-only)'), ('private', 'Private')], default="public'", help_text='Public: Any registered user can view and join a public group.<br>Public (invite-only):Any registered user can view the group.  Only invited users can join or make a request to group owner.<br>Private: Registered users cannot see any details about the group, including membership.  Only invited users can join.', max_length=15, verbose_name='Access'),
        ),
    ]
