# Generated by Django 3.2.14 on 2023-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20220613_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='logo',
            field=models.ImageField(blank=True, upload_to='people_group', verbose_name='Logo'),
        ),
    ]
