# Generated by Django 3.2.13 on 2022-04-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0001_initial'),
        ('services', '0025_auto_20220308_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='access_constraints',
        ),
        migrations.RemoveField(
            model_name='service',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='service',
            name='connection_params',
        ),
        migrations.RemoveField(
            model_name='service',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='service',
            name='first_noanswer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='noanswer_retries',
        ),
        migrations.RemoveField(
            model_name='service',
            name='online_resource',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='service',
            name='password',
        ),
        migrations.RemoveField(
            model_name='service',
            name='probe',
        ),
        migrations.RemoveField(
            model_name='service',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='service',
            name='proxy_base',
        ),
        migrations.RemoveField(
            model_name='service',
            name='resources_ref',
        ),
        migrations.RemoveField(
            model_name='service',
            name='store_ref',
        ),
        migrations.RemoveField(
            model_name='service',
            name='username',
        ),
        migrations.RemoveField(
            model_name='service',
            name='workspace_ref',
        ),
        migrations.AddField(
            model_name='service',
            name='harvester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_harvester', to='harvesting.harvester'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('WMS', 'Web Map Service'), ('GN_WMS', 'GeoNode (Web Map Service)'), ('REST_MAP', 'ArcGIS REST MapServer'), ('REST_IMG', 'ArcGIS REST ImageServer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HarvestJob',
        ),
    ]
