# Generated by Django 2.2.24 on 2022-02-14 10:54

from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_harvestjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('add_resourcebase_from_service', 'Can add resources to Service'), ('change_resourcebase_metadata', 'Can change resources metadata'))},
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='details',
            field=models.TextField(blank=True, default='Resource is queued', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_queryparams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='operations',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='probe',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='service',
            name='proxy_base',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('CANCELLED', 'QUEUED'), ('IN_PROCESS', 'IN_PROCESS'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='QUEUED', max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('AUTO', 'Auto-detect'), ('OWS', 'Paired WMS/WFS/WCS'), ('WMS', 'Web Map Service'), ('CSW', 'Catalogue Service'), ('REST_MAP', 'ArcGIS REST MapServer'), ('REST_IMG', 'ArcGIS REST ImageServer'), ('OGP', 'OpenGeoPortal'), ('HGL', 'Harvard Geospatial Library'), ('GN_WMS', 'GeoNode (Web Map Service)'), ('GN_CSW', 'GeoNode (Catalogue Service)')], max_length=10),
        ),
    ]
