# Generated by Django 3.2.14 on 2022-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20220720_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='operations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
