# Generated by Django 2.2.27 on 2022-07-20 02:56

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20220720_0956'),
        ('harvesting', '0003_harvestingsession_total_records_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsynchronousHarvestingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('harvesting', 'harvesting'), ('discover-harvestable-resources', 'discover-harvestable-resources')], editable=False, max_length=50)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('on-going', 'on-going'), ('finished-all-ok', 'finished-all-ok'), ('finished-all-failed', 'finished-all-failed'), ('finished-some-failed', 'finished-some-failed'), ('aborting', 'aborting'), ('aborted', 'aborted')], default='pending', editable=False, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('total_records_to_process', models.IntegerField(default=0, editable=False, help_text='Number of records being processed in this session')),
                ('records_done', models.IntegerField(default=0, help_text='Number of records that have already been processed')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestableResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(help_text='Identifier that allows referencing the resource on its remote service in a unique fashion. This is usually automatically filled by the harvester worker. The harvester worker needs to know how to either read or generate this from each remote resource in order to be able to compare the availability of resources between consecutive harvesting sessions.', max_length=255)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('updating-harvestable-resource', 'updating-harvestable-resource'), ('harvesting-resource', 'harvesting-resource')], default='ready', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, max_length=2000)),
                ('should_be_harvested', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_refreshed', models.DateTimeField()),
                ('last_harvested', models.DateTimeField(blank=True, null=True)),
                ('last_harvesting_message', models.TextField(blank=True)),
                ('last_harvesting_succeeded', models.BooleanField(default=False)),
                ('remote_resource_type', models.CharField(blank=True, help_text='Type of the resource in the remote service. Each harvester worker knows how to fill this field, in accordance with the resources for which harvesting is supported', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='harvestingsession',
            name='harvester',
        ),
        migrations.RemoveField(
            model_name='harvester',
            name='default_access_permissions',
        ),
        migrations.RemoveField(
            model_name='harvester',
            name='update_frequency',
        ),
        migrations.AddField(
            model_name='harvester',
            name='check_availability_frequency',
            field=models.PositiveIntegerField(default=10, help_text='How often (in minutes) should the remote service be checked for availability?'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='delete_orphan_resources_automatically',
            field=models.BooleanField(default=False, help_text='Orphan resources are those that have previously been created by means of a harvesting operation but that GeoNode can no longer find on the remote service being harvested. Should these resources be deleted from GeoNode automatically? This also applies to when a harvester configuration is deleted, in which case all of the resources that originated from that harvester are now considered to be orphan.'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='harvest_new_resources_by_default',
            field=models.BooleanField(default=False, help_text='Should new resources be harvested automatically without explicit selection?'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='harvesting_session_update_frequency',
            field=models.PositiveIntegerField(default=60, help_text='How often (in minutes) should new harvesting sessions be automatically scheduled?'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_check_harvestable_resources_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_checked_availability',
            field=models.DateTimeField(blank=True, help_text='Last time the remote server was checked for availability', null=True),
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_checked_harvestable_resources',
            field=models.DateTimeField(blank=True, help_text='Last time the remote server was checked for harvestable resources', null=True),
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date of last update to the harvester configuration.'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='num_harvestable_resources',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='harvester',
            name='refresh_harvestable_resources_update_frequency',
            field=models.PositiveIntegerField(default=30, help_text='How often (in minutes) should new refresh sessions be automatically scheduled?'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='remote_available',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the remote service is known to be available or not'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('updating-harvestable-resources', 'updating-harvestable-resources'), ('aborting-update-harvestable-resources', 'aborting-update-harvestable-resources'), ('harvesting-resources', 'harvesting-resources'), ('aborting-harvesting-resources', 'aborting-harvesting-resources'), ('checking-availability', 'checking-availability')], default='ready', max_length=50),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='harvester_type',
            field=models.CharField(choices=[('geonode.harvesting.harvesters.geonodeharvester.GeonodeUnifiedHarvesterWorker', 'geonode.harvesting.harvesters.geonodeharvester.GeonodeUnifiedHarvesterWorker'), ('geonode.harvesting.harvesters.wms.OgcWmsHarvester', 'geonode.harvesting.harvesters.wms.OgcWmsHarvester'), ('geonode.harvesting.harvesters.arcgis.ArcgisHarvesterWorker', 'geonode.harvesting.harvesters.arcgis.ArcgisHarvesterWorker')], default='geonode.harvesting.harvesters.geonodeharvester.GeonodeUnifiedHarvesterWorker', help_text='Harvester class used to perform harvesting sessions. New harvester types can be added by an admin by changing the main GeoNode `settings.py` file', max_length=255),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='harvester_type_specific_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration specific to each harvester type. Please consult GeoNode documentation on harvesting for more info. This field is mandatory, so at the very least an empty object (i.e. {}) must be supplied.'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='name',
            field=models.CharField(help_text='Harvester name', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='harvester',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
        migrations.DeleteModel(
            name='HarvestingSession',
        ),
        migrations.AddField(
            model_name='harvestableresource',
            name='geonode_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ResourceBase'),
        ),
        migrations.AddField(
            model_name='harvestableresource',
            name='harvester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvestable_resources', to='harvesting.Harvester'),
        ),
        migrations.AddField(
            model_name='asynchronousharvestingsession',
            name='harvester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='harvesting.Harvester'),
        ),
        migrations.AddConstraint(
            model_name='harvestableresource',
            constraint=models.UniqueConstraint(fields=('harvester', 'unique_identifier'), name='unique_id_for_harvester'),
        ),
    ]
