# Generated by Django 3.2.14 on 2022-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0004_auto_20220720_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='harvester_type_specific_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration specific to each harvester type. Please consult GeoNode documentation on harvesting for more info. This field is mandatory, so at the very least an empty object (i.e. {}) must be supplied.'),
        ),
    ]
