# Generated by Django 2.2.27 on 2022-05-11 11:51

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, default='About SDI', max_length=255, null=True, verbose_name='Title Page')),
                ('header_title_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None, verbose_name='Set the text color of the title')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Content of the About page')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'SDI About',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, default='Frequently Asked Questions', max_length=255, null=True, verbose_name='Title Page')),
                ('header_title_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None, verbose_name='Set the text color of the title')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Content of the FAQs page')),
                ('authenticated_users', models.BooleanField(choices=[(False, 'For anyone including not a registered user'), (True, 'Certainly yes!')], default=True, verbose_name='Display for registered users?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'SDI FAQs',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, default='Help & Support', max_length=255, null=True, verbose_name='Title Page')),
                ('header_title_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None, verbose_name='Set the text color of the title')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Content of the Help & Support page')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'SDI Help & Support',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Choose an area')),
                ('details', models.TextField(blank=True, help_text='please include as much information as possible..', null=True, verbose_name='Details')),
                ('feedback_url', models.URLField(blank=True, help_text='provide the url when the trouble happens', max_length=255, null=True, verbose_name='URL')),
                ('feedback_file', models.FileField(blank=True, max_length=255, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='add a Screenshot or Video (recommended)')),
                ('extension', models.CharField(blank=True, max_length=128, null=True)),
                ('feedback_type', models.CharField(blank=True, max_length=128, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
