geofenceVendorAdapter.databasePlatform=org.hibernatespatial.postgis.PostgisDialect
geofenceDataSource.driverClassName=org.postgresql.Driver
geofenceDataSource.url=jdbc:postgresql://{DB_CMS_HOST}:{DB_CMS_PORT}/{GEONODE_DATABASE_GF}
geofenceDataSource.username={GEONODE_DATABASE}
geofenceDataSource.password={GEONODE_DATABASE_PASSWORD}
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]={GEONODE_GEODATABASE_SCHEMA}

# avoid hibernate transaction issues
geofenceDataSource.testOnBorrow=true
geofenceDataSource.validationQuery=SELECT 1
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.testOnBorrow]=true
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.validationQuery]=SELECT 1