# Generated by Django 2.2.16 on 2021-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_set_contributors_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('id', 'Bahasa Indonesia')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
