# Generated by Django 2.2.24 on 2022-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_auto_20210524_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.TextField(blank=True, help_text='introduce yourself', null=True, verbose_name='Profile'),
        ),
    ]
