# Generated by Django 2.2.24 on 2022-04-05 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_auto_20220308_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSizeLimit',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('max_size', models.BigIntegerField(default=1848576000, help_text='The maximum file size allowed for upload (bytes).', validators=[django.core.validators.MinValueValidator(limit_value=0)])),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.AddField(
            model_name='upload',
            name='store_spatial_files',
            field=models.BooleanField(default=True),
        ),
    ]
