# Generated by Django 3.2.13 on 2022-04-19 07:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20220405_1505'),
        ('upload', '0026_auto_20220405_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadParallelismLimit',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('max_number', models.PositiveSmallIntegerField(default=10, help_text='The maximum number of parallel uploads (0 to 32767).')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.RemoveField(
            model_name='upload',
            name='layer',
        ),
        migrations.AddField(
            model_name='upload',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadsizelimit',
            name='max_size',
            field=models.PositiveBigIntegerField(default=2848576000, help_text='The maximum file size allowed for upload (bytes).'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
