# Generated by Django 2.2.24 on 2022-02-14 10:54

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_auto_20210524_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='resume_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_dir',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=4096, storage=django.core.files.storage.FileSystemStorage(base_url='/uploaded/'), upload_to='layers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='slug',
            field=models.SlugField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
    ]
