# Generated by Django 3.2.14 on 2022-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20220720_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsizelimit',
            name='max_size',
            field=models.PositiveBigIntegerField(default=5368709120, help_text='The maximum file size allowed for upload (bytes).'),
        ),
    ]
