# Generated by Django 2.2.16 on 2021-05-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_upload_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='append_to_mosaic_name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='append_to_mosaic_opts',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='mosaic',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='base',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='upload',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.Upload'),
        ),
    ]
