# Generated by Django 2.2.24 on 2022-04-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20220308_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='was_approved',
            field=models.BooleanField(default=True, help_text='previous approved state.', null=True, verbose_name='was approved'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='was_published',
            field=models.BooleanField(default=True, help_text='previous published state.', null=True, verbose_name='was published'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_resource', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='ExtraMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='Additional metadata, must be in format [ {"metadata_key": "metadata_value"}, {"metadata_key": "metadata_value"} ]', null=True, to='base.ExtraMetadata', verbose_name='Extra Metadata'),
        ),
    ]
