# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:29


from django.db import migrations, models
import django.db.models.deletion
import django.contrib.gis.db.models.fields

class Migration(migrations.Migration):

    dependencies = [
        ('base', '24_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('blank_target', models.BooleanField()),
                ('url', models.CharField(max_length=2000)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('description_en', models.TextField(default='', null=True)),
                ('gn_description', models.TextField(default='', null=True, verbose_name='SDI description')),
                ('gn_description_en', models.TextField(default='', null=True, verbose_name='SDI description')),
                ('is_choice', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Metadata Type of Data',
                'ordering': ('identifier',),
            },
        ),
    ]

