# Generated by Django 2.2.24 on 2022-02-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '24_to_26'),
        ('base', '0027_auto_20170801_1218'),
    ]

    operations = [
    ]
