# Generated by Django 2.2.27 on 2022-05-11 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonfield_backport.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='date_content',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='description_en',
        ),
        migrations.AddField(
            model_name='datatype',
            name='title',
            field=models.CharField(default='', help_text='one or more words used to represent the data type for grouping the Dataset.', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='title_en',
            field=models.CharField(default='', help_text='one or more words used to represent the data type for grouping the Dataset.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='blob',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='data_citation',
            field=models.CharField(blank=True, help_text='key descriptive information to acknowledge the original author/producer and to help other researchers find the resource. Provide the standards rule such as: author, title, edition or version, publication year, publisher, doi, access date and time.', max_length=2048, null=True, verbose_name='Data Citation'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_distribution',
            field=models.CharField(blank=True, help_text='date or time period that the work was made available for distribution/presentation.', max_length=255, null=True, verbose_name='Distribution Date'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='distributor',
            field=models.CharField(blank=True, help_text='the organizatino designated by the author or producer to generate copies of the particular work including any necessary editions or revisions.', max_length=255, null=True, verbose_name='Distributor'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='files',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='project_information',
            field=models.CharField(blank=True, help_text='name of project with which the research is affiliated.', max_length=255, null=True, verbose_name='Project Information'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='related_publication',
            field=models.TextField(blank=True, help_text='publication(s): article link, journal, or data citation that use the data from this Dataset.', max_length=2000, null=True, verbose_name='Related Publication'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='remote_typename',
            field=models.CharField(blank=True, help_text='Name of the Remote Service if any.', max_length=512, null=True, verbose_name='Remote Service Typename'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='sourcetype',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('REMOTE', 'REMOTE'), ('COPYREMOTE', 'COPYREMOTE')], default='LOCAL', help_text='The resource source type, which can be one of "LOCAL", "REMOTE" or "COPYREMOTE".', max_length=16, verbose_name='Source Type'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='state',
            field=models.CharField(choices=[('READY', 'READY'), ('RUNNING', 'RUNNING'), ('PENDING', 'PENDING'), ('WAITING', 'WAITING'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE'), ('INVALID', 'INVALID'), ('PROCESSED', 'PROCESSED')], default='READY', help_text='Hold the resource processing state.', max_length=16, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='svg',
            field=models.TextField(blank=True, help_text="SVG element tag wrapped in <svg viewBox='0 0 24 24'>...</svg>. Copy paste the icon from Figma, Sketch, AI and other Vector Graphics Software.", null=True, verbose_name='SVG element tag (optional if Font Awesome Icon is not available)'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='title',
            field=models.TextField(default='', help_text='one or more words used to represent the classification scheme for grouping the Dataset.', verbose_name='Topic Category title'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='title_en',
            field=models.TextField(default='', help_text='one or more words used to represent the classification scheme for grouping the Dataset.', null=True, verbose_name='Topic Category title'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='gn_description',
            field=models.TextField(default='', help_text='high-level description of data type to assist in the grouping of available Dataset.', null=True, verbose_name='High-level description of Data Type'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='gn_description_en',
            field=models.TextField(default='', help_text='high-level description of data type to assist in the grouping of available Dataset.', null=True, verbose_name='High-level description of Data Type'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='identifier',
            field=models.CharField(default='dataType', max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='is_choice',
            field=models.BooleanField(choices=[(False, 'Not available to choose. Required by system to automatically classify the uncategorized Dataset.'), (True, 'Certainly yes!')], default=True, help_text='should be available to choose for grouping the Dataset.', verbose_name='Data Type available to choose?'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='abstract',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the Dataset.', max_length=2000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='author',
            field=models.CharField(blank=True, help_text='the data custodian, people(s), corporate body(ies) or agency(ies) responsible for creating the work.', max_length=2048, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='constraints_other',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the Dataset or metadata.', null=True, verbose_name='Restrictions Other'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='contacts',
            field=models.ManyToManyField(through='base.ContactRole', to=settings.AUTH_USER_MODEL, verbose_name='the contact for this Dataset.'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_insert_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='CSW Insert Date'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_mdsource',
            field=models.CharField(default='local', max_length=256, verbose_name='CSW Source'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_schema',
            field=models.CharField(default='http://www.isotc211.org/2005/gmd', max_length=64, verbose_name='CSW Schema'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_type',
            field=models.CharField(choices=[('series', 'series'), ('software', 'computer program or routine'), ('featureType', 'feature type'), ('model', 'copy or imitation of an existing or hypothetical object'), ('collectionHardware', 'collection hardware'), ('collectionSession', 'collection session'), ('nonGeographicDataset', 'non-geographic data'), ('propertyType', 'property type'), ('fieldSession', 'field session'), ('dataset', 'dataset'), ('service', 'service interfaces'), ('attribute', 'attribute class'), ('attributeType', 'characteristic of a feature'), ('tile', 'tile or spatial subset of geographic data'), ('feature', 'feature'), ('dimensionGroup', 'dimension group')], default='dataset', max_length=32, verbose_name='CSW Type'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_typename',
            field=models.CharField(default='gmd:MD_Metadata', max_length=32, verbose_name='CSW Typename'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='csw_wkt_geometry',
            field=models.TextField(default='POLYGON((-180 -90,-180 90,180 90,180 -90,-180 -90))', verbose_name='CSW WKT Geometry'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='data_description',
            field=models.TextField(blank=True, help_text='a summary describing the nature, scope or methodology of the Dataset', max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='data_quality_statement',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of the Dataset.", max_length=2000, null=True, verbose_name='Data Quality Statement'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='data_type',
            field=models.ForeignKey(blank=True, help_text='type of data included in the file.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DataType'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='the publication/creation/revision of a dataset.', verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='date_type',
            field=models.CharField(choices=[('creation', 'Creation'), ('publication', 'Publication'), ('revision', 'Revision')], default='publication', help_text='identification of when a given event occurred.', max_length=255, verbose_name='Date Type'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='dirty_state',
            field=models.BooleanField(default=False, help_text='Security Rules Are Not Synced with GeoServer!', verbose_name='Dirty State'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='edition',
            field=models.CharField(blank=True, help_text='version of the Dataset.', max_length=255, null=True, verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='featured',
            field=models.BooleanField(default=False, help_text='should this Dataset be advertised in home page?', verbose_name='Advertised to Homepage'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='is this Dataset validated from a publisher or editor?', verbose_name='Validated from a publisher or editor?'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='is_published',
            field=models.BooleanField(default=True, help_text='should this Dataset be published and searchable?', verbose_name='Should be Published and Searchable?'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='commonly used word(s) or formalised word(s) or phrase(s) used to describe the Dataset (space or comma-separated).', through='base.TaggedContentItem', to='base.HierarchicalKeyword', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('ind', 'Indonesian')], default='eng', help_text='language used within the Dataset.', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='license',
            field=models.ForeignKey(blank=True, help_text='outlines how this data can be used once downloaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.License', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='maintenance_frequency',
            field=models.CharField(blank=True, choices=[('unknown', 'frequency of maintenance for the data is not known'), ('continual', 'data is repeatedly and frequently updated'), ('notPlanned', 'there are no plans to update the data'), ('asNeeded', 'data is updated as deemed necessary'), ('daily', 'data is updated each day'), ('weekly', 'data is updated on a weekly basis'), ('fortnightly', 'data is updated every two weeks'), ('monthly', 'data is updated each month'), ('biannually', 'data is updated twice each year'), ('quarterly', 'data is updated every three months'), ('annually', 'data is updated every year')], help_text='information about maintenance and update frequency of the dataset.', max_length=255, null=True, verbose_name='Maintenance Frequency'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='additional metadata, must be in format [ {"metadata_key": "metadata_value"}, {"metadata_key": "metadata_value"} ].', null=True, to='base.ExtraMetadata', verbose_name='Extra Metadata'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata_only',
            field=models.BooleanField(default=False, help_text='should this Dataset be excluded from search?', verbose_name='Excluded from Search'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata_uploaded_preserve',
            field=models.BooleanField(default=False, help_text='preserved Spatial Metadata XML file (a subset of ISO, FGDC, and Dublin Core metadata elements). Once it set, the metadata cannot be edited.', verbose_name='Metadata Uploaded Preserve'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_resource', to=settings.AUTH_USER_MODEL, verbose_name='the owner for this Dataset.'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='purpose',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the Dataset(s) was developed.', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='keyword identifies a location.', null=True, to='base.Region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, help_text='limitation(s) placed upon the access or use of the Dataset.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.RestrictionCodeType', verbose_name='Restrictions'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='source',
            field=models.CharField(blank=True, help_text='people/organizations that contributed to the Dataset (separate by commas), from which institutions the data was obtained.', max_length=2048, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='spatial_representation_type',
            field=models.ForeignKey(blank=True, help_text='method used to represent geographic information in the dataset.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SpatialRepresentationType', verbose_name='Spatial Representation Type'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='spatial_resolution',
            field=models.CharField(blank=True, help_text='describes the spatial resolution: e.g. 1:50.000 or 30m.', max_length=255, null=True, verbose_name='Spatial Resolution/Scale'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='supplemental_information',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, verbose_name='Supplemental Information'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='temporal_extent_end',
            field=models.DateTimeField(blank=True, help_text='time period covered by the content of the dataset (end).', null=True, verbose_name='Temporal Extent End'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='temporal_extent_start',
            field=models.DateTimeField(blank=True, help_text='time period covered by the content of the dataset (start).', null=True, verbose_name='Temporal Extent Start'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='title',
            field=models.CharField(help_text='full title by which the Dataset is known.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='tkeywords',
            field=models.ManyToManyField(blank=True, help_text='formalised word(s) or phrase(s) from a fixed thesaurus used to describe the subject (space or comma-separated).', null=True, to='base.ThesaurusKeyword', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='was_approved',
            field=models.BooleanField(default=True, help_text='previous approved state.', null=True, verbose_name='Was Approved'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='was_published',
            field=models.BooleanField(default=True, help_text='previous published state.', null=True, verbose_name='Was Published'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='fa_class',
            field=models.CharField(default='times', help_text='font awesome v6 icon name. See more https://fontawesome.com/search?m=free&s=solid%2Cbrands. Provide only the name, i.e: home, database', max_length=64, verbose_name='Font Awesome v6 free icon name'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description',
            field=models.TextField(default='', help_text='high-level description of classification scheme to assist in the grouping and topic-based search of available Dataset.', null=True, verbose_name='High-level description of Classification Scheme'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description_en',
            field=models.TextField(default='', help_text='high-level description of classification scheme to assist in the grouping and topic-based search of available Dataset.', null=True, verbose_name='High-level description of Classification Scheme'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='is_choice',
            field=models.BooleanField(choices=[(False, 'Not available to choose. Required by system to automatically classify the uncategorized Dataset.'), (True, 'Certainly yes!')], default=True, help_text='should be available to choose for grouping the Dataset.', verbose_name='Classification Schemes available to choose?'),
        ),
    ]
