# Generated by Django 2.2.27 on 2022-05-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccategory',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
