# Generated by Django 2.2.24 on 2022-02-14 11:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_merge_20220214_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='CuratedThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='curated_thumbs')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column='wkt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ThesaurusLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Thesaurus Labels',
                'ordering': ('lang',),
            },
        ),
        migrations.CreateModel(
            name='UserGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column='wkt')),
            ],
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
        migrations.AlterModelOptions(
            name='resourcebase',
            options={'permissions': (('change_resourcebase_permissions', 'Can change resource permissions'), ('download_resourcebase', 'Can download resource'), ('publish_resourcebase', 'Can publish resource'), ('change_resourcebase_metadata', 'Can change resource metadata'))},
        ),
        migrations.AlterModelOptions(
            name='thesauruskeywordlabel',
            options={'ordering': ('keyword', 'lang'), 'verbose_name_plural': 'Thesaurus Keyword Labels'},
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_x0',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_x1',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_y0',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_y1',
        ),
        migrations.AddField(
            model_name='menu',
            name='placeholder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.MenuPlaceholder'),
        ),
        migrations.AddField(
            model_name='region',
            name='bbox_x0',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='bbox_x1',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='bbox_y0',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='bbox_y1',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='srid',
            field=models.CharField(default='EPSG:4326', max_length=30),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='alternate',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='author',
            field=models.CharField(blank=True, help_text='data custodian or people/organizations that contributed to the data set (separated by commas). A short description rather than source column.', max_length=2048, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='bbox_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='high-level geographic data thematic classification to assist in the grouping and search of available geographic data sets.', null=True, to='base.TopicCategory'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='data_description',
            field=models.TextField(blank=True, help_text='description or abstract of the data and methodology', max_length=2000, null=True, verbose_name='data description'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='data_type',
            field=models.ForeignKey(blank=True, help_text='type of your data.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.DataType'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_content',
            field=models.CharField(blank=True, help_text='date or time period that the data represents', max_length=255, null=True, verbose_name='date of content'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='dirty_state',
            field=models.BooleanField(default=False, help_text='Security Rules Are Not Synched with GeoServer!', verbose_name='Dirty State'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='doi',
            field=models.CharField(blank=True, help_text='a DOI will be added by Admin before publication.', max_length=255, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='is this resource validated from a publisher or editor?', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='metadata_only',
            field=models.BooleanField(default=False, help_text='if true, will be excluded from search', verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='resource_type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Resource Type'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='source',
            field=models.CharField(blank=True, help_text='people/organizations that contributed to the data set (separate by commas), or link to the journal article, from which institutions the data was obtained', max_length=2048, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='spatial_resolution',
            field=models.CharField(blank=True, help_text='describes the spatial resolution: e.g. 1:50.000 or 30m', max_length=255, null=True, verbose_name='Spatial resolution/scale'),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='card_max',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='card_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='facet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='abstract',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='constraints_other',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='Restrictions other'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='data_quality_statement',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='Data quality statement'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='featured',
            field=models.BooleanField(default=False, help_text='should this resource be advertised in home page?', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='is_published',
            field=models.BooleanField(default=True, help_text='should this resource be published and searchable?', verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='commonly used word(s) or formalised word(s) or phrase(s) used to describe the subject (space or comma-separated)', through='base.TaggedContentItem', to='base.HierarchicalKeyword', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('ind', 'Indonesian')], default='eng', help_text='language used within the dataset', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='license',
            field=models.ForeignKey(blank=True, help_text='license of the dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.License', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='maintenance_frequency',
            field=models.CharField(blank=True, choices=[('unknown', 'frequency of maintenance for the data is not known'), ('continual', 'data is repeatedly and frequently updated'), ('notPlanned', 'there are no plans to update the data'), ('asNeeded', 'data is updated as deemed necessary'), ('daily', 'data is updated each day'), ('weekly', 'data is updated on a weekly basis'), ('fortnightly', 'data is updated every two weeks'), ('monthly', 'data is updated each month'), ('biannually', 'data is updated twice each year'), ('quarterly', 'data is updated every three months'), ('annually', 'data is updated every year')], help_text='Information about maintenance and update frequency of the dataset', max_length=255, null=True, verbose_name='maintenance frequency'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata_uploaded_preserve',
            field=models.BooleanField(default=False, verbose_name='Metadata uploaded preserve'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_resource', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='purpose',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='keyword identifies a location', null=True, to='base.Region', verbose_name='keywords region'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, help_text='limitation(s) placed upon the access or use of the data.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.RestrictionCodeType', verbose_name='Restrictions'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='spatial_representation_type',
            field=models.ForeignKey(blank=True, help_text='method used to represent geographic information in the dataset.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.SpatialRepresentationType', verbose_name='Spatial representation type'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='srid',
            field=models.CharField(default='EPSG:4326', max_length=30),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='supplemental_information',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, verbose_name='Supplemental information'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='temporal_extent_end',
            field=models.DateTimeField(blank=True, help_text='time period covered by the content of the dataset (end)', null=True, verbose_name='Temporal extent end'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='temporal_extent_start',
            field=models.DateTimeField(blank=True, help_text='time period covered by the content of the dataset (start)', null=True, verbose_name='Temporal extent start'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True, verbose_name='Thumbnail url'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='tkeywords',
            field=models.ManyToManyField(blank=True, help_text='formalised word(s) or phrase(s) from a fixed thesaurus used to describe the subject (space or comma-separated)', null=True, to='base.ThesaurusKeyword', verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='gn_description',
            field=models.TextField(max_length=255, verbose_name='SDI description'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='gn_description_en',
            field=models.TextField(max_length=255, null=True, verbose_name='SDI description'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='gn_description',
            field=models.CharField(max_length=255, verbose_name='SDI description'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='gn_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='SDI description'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thesaurus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description',
            field=models.TextField(default='', null=True, verbose_name='SDI description'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description_en',
            field=models.TextField(default='', null=True, verbose_name='SDI description'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('placeholder', 'title'), ('placeholder', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('menu', 'title'), ('menu', 'order')},
        ),
        migrations.AddField(
            model_name='usergeolimit',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AddField(
            model_name='usergeolimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thesauruslabel',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_thesaurus', to='base.Thesaurus'),
        ),
        migrations.AddField(
            model_name='groupgeolimit',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AddField(
            model_name='curatedthumbnail',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='groups_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_geolimits', to='base.GroupGeoLimit'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='users_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_geolimits', to='base.UserGeoLimit'),
        ),
        migrations.AlterUniqueTogether(
            name='thesauruslabel',
            unique_together={('thesaurus', 'lang')},
        ),
    ]
