# Generated by Django 2.2.27 on 2022-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20220511_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='identifier',
            field=models.CharField(default='DataType', help_text='identifier database field. write the convention using CamelCase style, i.e.: DerivedData, ObservationalData', max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='title',
            field=models.CharField(default='', help_text='one or more words used to represent the data type for grouping the Dataset.', max_length=255, verbose_name='Data Type Title'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='title_en',
            field=models.CharField(default='', help_text='one or more words used to represent the data type for grouping the Dataset.', max_length=255, null=True, verbose_name='Data Type Title'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='distributor',
            field=models.CharField(blank=True, help_text='the organization designated by the author or producer to generate copies of the particular work including any necessary editions or revisions.', max_length=255, null=True, verbose_name='Distributor'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='supplemental_information',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the Dataset.', max_length=2000, verbose_name='Supplemental Information'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='fa_class',
            field=models.CharField(default='times', help_text="font awesome v6 icon name. See more <a href='https://fontawesome.com/search?m=free&s=solid%2Cbrands' target='_blank'>here</a>. Provide only the name, i.e: home, database", max_length=64, verbose_name='Font Awesome v6 free icon name'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='identifier',
            field=models.CharField(default='location', help_text='identifier database field. write the convention using CamelCase style, i.e.: GreenEconomy, SustainabilityPractice', max_length=255),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='svg',
            field=models.TextField(blank=True, help_text="SVG element tag wrapped in < svg viewBox='0 0 24 24' >...< /svg >. Copy paste the icon from Figma, Sketch, AI and other Vector Graphics Software.", null=True, verbose_name='SVG element tag (optional if Font Awesome Icon is not available)'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title',
            field=models.TextField(default='', help_text='one or more words used to represent the classification scheme for grouping the Dataset.', verbose_name='Topic Category Title'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title_en',
            field=models.TextField(default='', help_text='one or more words used to represent the classification scheme for grouping the Dataset.', null=True, verbose_name='Topic Category Title'),
        ),
    ]
