# Generated by Django 2.2.27 on 2022-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220512_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restrictioncodetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restrictioncodetype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='spatialrepresentationtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spatialrepresentationtype',
            name='description_en',
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='title',
            field=models.TextField(default='', editable=False, help_text='one or more words used to represent the Restriction type for grouping the Dataset.', max_length=255, verbose_name='Restriction Title'),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='title_en',
            field=models.TextField(default='', editable=False, help_text='one or more words used to represent the Restriction type for grouping the Dataset.', max_length=255, null=True, verbose_name='Restriction Title'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='title',
            field=models.CharField(default='', editable=False, help_text='one or more words used to represent the Spatial Representation type for grouping the Dataset.', max_length=255, verbose_name='Spatial Representation Title'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='title_en',
            field=models.CharField(default='', editable=False, help_text='one or more words used to represent the Spatial Representation type for grouping the Dataset.', max_length=255, null=True, verbose_name='Spatial Representation Title'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='title',
            field=models.CharField(default='', help_text='one or more words used to represent the Data Type for grouping the Dataset.', max_length=255, verbose_name='Data Type Title'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='title_en',
            field=models.CharField(default='', help_text='one or more words used to represent the Data Type for grouping the Dataset.', max_length=255, null=True, verbose_name='Data Type Title'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='gn_description',
            field=models.TextField(help_text='high-level description of data type to assist in the grouping of available Dataset.', max_length=255, verbose_name='High-level description of Restriction'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='gn_description_en',
            field=models.TextField(help_text='high-level description of data type to assist in the grouping of available Dataset.', max_length=255, null=True, verbose_name='High-level description of Restriction'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='identifier',
            field=models.CharField(help_text='identifier database field. write the convention using CamelCase style, i.e.: intellectualPropertyRights, patentPending, restricted', max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='gn_description',
            field=models.CharField(help_text='high-level description of Spatial Representation to assist in the grouping of available Dataset.', max_length=255, verbose_name='High-level description of Spatial Representation'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='gn_description_en',
            field=models.CharField(help_text='high-level description of Spatial Representation to assist in the grouping of available Dataset.', max_length=255, null=True, verbose_name='High-level description of Spatial Representation'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='identifier',
            field=models.CharField(help_text='identifier database field. write the convention using CamelCase style, i.e.: vector, grid, textTable', max_length=255),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description',
            field=models.TextField(default='', help_text='high-level description of Topic/Information Categories to assist in the grouping and topic-based search of available Dataset.', null=True, verbose_name='High-level description of Topic/Information categories'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='gn_description_en',
            field=models.TextField(default='', help_text='high-level description of Topic/Information Categories to assist in the grouping and topic-based search of available Dataset.', null=True, verbose_name='High-level description of Topic/Information categories'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='is_choice',
            field=models.BooleanField(choices=[(False, 'Not available to choose. Required by system to automatically classify the uncategorized Dataset.'), (True, 'Certainly yes!')], default=True, help_text='should be available to choose for grouping the Dataset.', verbose_name='Topic/Information Categoriess available to choose?'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title',
            field=models.TextField(default='', help_text='one or more words used to represent the Topic/Information Categories for grouping the Dataset.', verbose_name='Topic Category Title'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title_en',
            field=models.TextField(default='', help_text='one or more words used to represent the Topic/Information Categories for grouping the Dataset.', null=True, verbose_name='Topic Category Title'),
        ),
    ]
