# Generated by Django 2.2.27 on 2022-07-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20220711_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='title',
            field=models.TextField(default='', help_text='one or more words used to represent the Restriction type for grouping the Dataset.', max_length=255, verbose_name='Restriction Title'),
        ),
        migrations.AlterField(
            model_name='restrictioncodetype',
            name='title_en',
            field=models.TextField(default='', help_text='one or more words used to represent the Restriction type for grouping the Dataset.', max_length=255, null=True, verbose_name='Restriction Title'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='title',
            field=models.CharField(default='', help_text='one or more words used to represent the Spatial Representation type for grouping the Dataset.', max_length=255, verbose_name='Spatial Representation Title'),
        ),
        migrations.AlterField(
            model_name='spatialrepresentationtype',
            name='title_en',
            field=models.CharField(default='', help_text='one or more words used to represent the Spatial Representation type for grouping the Dataset.', max_length=255, null=True, verbose_name='Spatial Representation Title'),
        ),
    ]
