# Generated by Django 2.2.27 on 2022-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20220720_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='subtype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
