# Generated by Django 3.2.14 on 2022-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_resourcebase_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrametadata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='blob',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
