# Generated by Django 3.2.14 on 2022-07-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20220721_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='thumbnail_path',
            field=models.TextField(blank=True, null=True, verbose_name='Thumbnail path'),
        ),
    ]
