# Generated by Django 3.2.14 on 2022-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_resourcebase_thumbnail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedthumbnail',
            name='img',
            field=models.ImageField(upload_to='thumbs'),
        ),
    ]
