# Generated by Django 3.2.14 on 2022-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_curatedthumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='hash',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='CuratedThumbnail',
        ),
    ]
