# Generated by Django 3.2.14 on 2022-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20220803_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
