# Generated by Django 3.2.14 on 2022-09-08 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0037_alter_resourcebase_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=1.0, verbose_name='Version')),
                ('summary', models.TextField(default='', help_text='a summary of the changes that user are committing to change the resource', verbose_name='Summary')),
                ('description', models.TextField(default='', help_text='write one sentence describing the change that you are committing', verbose_name='Description')),
                ('tags', models.CharField(blank=True, choices=[('replace', 'Replace Dataset'), ('edit', 'Edit Metadata'), ('append', 'Append Data')], max_length=255, null=True, verbose_name='Tags')),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.resourcebase')),
            ],
            options={
                'verbose_name_plural': 'Datasets Versioning',
                'ordering': ['id'],
            },
        ),
    ]
