# Generated by Django 3.2.14 on 2022-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_resourceversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='supplemental_information',
            field=models.TextField(blank=True, help_text='any other descriptive information about the Dataset.', max_length=2000, null=True, verbose_name='Supplemental Information'),
        ),
        migrations.AlterField(
            model_name='resourceversion',
            name='version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Version'),
        ),
    ]
