# Generated by Django 3.2.14 on 2022-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20220909_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceversion',
            name='description',
        ),
        migrations.AddField(
            model_name='resourceversion',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='record all the field changes from previous version to the new one.', null=True),
        ),
        migrations.AlterField(
            model_name='resourceversion',
            name='summary',
            field=models.TextField(default='', help_text='write one sentence describing the change that you are committing', verbose_name='Summary'),
        ),
    ]
