# Generated by Django 2.2.16 on 2021-04-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_resourcebase_metadata_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='data_description',
            field=models.TextField(blank=True, default=20210101, help_text='description or abstract of the data and methodology', max_length=2000, verbose_name='data description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='date_content',
            field=models.CharField(blank=True, help_text='date or time period that the data represents', max_length=255, null=True, verbose_name='date of content'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('ind', 'Indonesian')], default='eng', help_text='language used within the dataset', max_length=3, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='maintenance_frequency',
            field=models.CharField(blank=True, choices=[('unknown', 'frequency of maintenance for the data is not known'), ('continual', 'data is repeatedly and frequently updated'), ('notPlanned', 'there are no plans to update the data'), ('asNeeded', 'data is updated as deemed necessary'), ('daily', 'data is updated each day'), ('annually', 'data is updated every year'), ('biannually', 'data is updated twice each year'), ('quarterly', 'data is updated every three months'), ('monthly', 'data is updated each month'), ('fortnightly', 'data is updated every two weeks'), ('weekly', 'data is updated on a weekly basis')], help_text='frequency with which modifications and deletions are made to the data after it is first produced', max_length=255, null=True, verbose_name='maintenance frequency'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='source',
            field=models.CharField(blank=True, help_text='People/organizations that contributed to the data set (separate by commas), or link to the journal article, from which institutions the data was obtained', max_length=2048, null=True, verbose_name='Source'),
        ),
    ]
