# Generated by Django 2.2.27 on 2022-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '24_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='maplayer',
            name='store',
            field=models.TextField(null=True, verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='map',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='map',
            name='constraints_other_en',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='Restrictions other'),
        ),
        migrations.AlterField(
            model_name='map',
            name='data_quality_statement_en',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='Data quality statement'),
        ),
        migrations.AlterField(
            model_name='map',
            name='purpose_en',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='map',
            name='supplemental_information_en',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='Supplemental information'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='format',
            field=models.TextField(blank=True, null=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='name',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='styles',
            field=models.TextField(blank=True, null=True, verbose_name='styles'),
        ),
        migrations.DeleteModel(
            name='MapSnapshot',
        ),
    ]
