# Generated by Django 2.2.27 on 2022-03-08 10:21

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Frequently Asked Questions', help_text='Title Page', max_length=255)),
                ('contents', models.TextField(blank=True, help_text='Content of the FAQs page', null=True)),
                ('header_title_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name_plural': 'SDI FAQs',
                'ordering': ('id',),
            },
        ),
    ]
