# Generated by Django 2.2.27 on 2022-03-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geonodefaq',
            options={'ordering': ('id',), 'verbose_name_plural': 'SDI FAQs'},
        ),
    ]
