# Generated by Django 2.2.27 on 2022-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='authenticated_users',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=True, verbose_name='Display for authenticated users'),
        ),
    ]
