# Generated by Django 2.2.27 on 2022-03-08 14:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='authenticated_users',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=True, verbose_name='Display for authenticated users'),
        ),
        migrations.AlterField(
            model_name='site',
            name='header_title_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
