# Generated by Django 2.2.27 on 2022-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20220308_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodefaq',
            name='name',
            field=models.CharField(default='FAQs', max_length=100),
        ),
    ]
