# Generated by Django 2.2.27 on 2022-03-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_geonodefaq_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodefaq',
            name='name',
        ),
    ]
