# Generated by Django 2.2.27 on 2022-03-08 12:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_remove_geonodefaq_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodefaq',
            name='header_title_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
