# Generated by Django 2.2.27 on 2022-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_geonodefaq_header_title_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodefaq',
            name='authenticated_users',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=True, verbose_name='Display for authenticated users'),
        ),
    ]
