# Generated by Django 2.2.27 on 2022-03-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0006_geonodefaq_authenticated_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodefaq',
            name='contents_color',
        ),
    ]
