# Generated by Django 2.2.27 on 2022-03-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0007_remove_geonodefaq_contents_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeonodeFaq',
            new_name='Site',
        ),
    ]
